# Generated by Django 6.0.7 on 2026-07-16 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Usuario',
            fields=[
                ('id_nomina', models.CharField(db_column='id_nomina', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TBL_Video',
            fields=[
                ('id_video', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=5)),
                ('tamano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TBL_Usuario_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='streaming.tbl_usuario')),
                ('id_video', models.ForeignKey(db_column='id_video', on_delete=django.db.models.deletion.CASCADE, to='streaming.tbl_video')),
            ],
        ),
    ]
