# Generated by Django 6.0.7 on 2026-07-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_video',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
